#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = 
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB) -lsfml-graphics -lsfml-window -lsfml-system
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/spacebattle

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O3
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB) -lsfml-graphics -lsfml-window -lsfml-system
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = spacebattle

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/bin/Collision.o $(OBJDIR_DEBUG)/bin/Game.o $(OBJDIR_DEBUG)/bin/GameOverState.o $(OBJDIR_DEBUG)/bin/GameState.o $(OBJDIR_DEBUG)/bin/AssetManager.o $(OBJDIR_DEBUG)/bin/InputManager.o $(OBJDIR_DEBUG)/bin/MainMenuState.o $(OBJDIR_DEBUG)/bin/SplashState.o $(OBJDIR_DEBUG)/bin/StateMachine.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/bin/Collision.o $(OBJDIR_RELEASE)/bin/Game.o $(OBJDIR_RELEASE)/bin/GameOverState.o $(OBJDIR_RELEASE)/bin/GameState.o $(OBJDIR_RELEASE)/bin/AssetManager.o $(OBJDIR_RELEASE)/bin/InputManager.o $(OBJDIR_RELEASE)/bin/MainMenuState.o $(OBJDIR_RELEASE)/bin/SplashState.o $(OBJDIR_RELEASE)/bin/StateMachine.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/bin || mkdir -p $(OBJDIR_DEBUG)/bin

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/bin/Collision.o: bin/Collision.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bin/Collision.cpp -o $(OBJDIR_DEBUG)/bin/Collision.o

$(OBJDIR_DEBUG)/bin/Game.o: bin/Game.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bin/Game.cpp -o $(OBJDIR_DEBUG)/bin/Game.o

$(OBJDIR_DEBUG)/bin/GameOverState.o: bin/GameOverState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bin/GameOverState.cpp -o $(OBJDIR_DEBUG)/bin/GameOverState.o

$(OBJDIR_DEBUG)/bin/GameState.o: bin/GameState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bin/GameState.cpp -o $(OBJDIR_DEBUG)/bin/GameState.o

$(OBJDIR_DEBUG)/bin/AssetManager.o: bin/AssetManager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bin/AssetManager.cpp -o $(OBJDIR_DEBUG)/bin/AssetManager.o

$(OBJDIR_DEBUG)/bin/InputManager.o: bin/InputManager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bin/InputManager.cpp -o $(OBJDIR_DEBUG)/bin/InputManager.o

$(OBJDIR_DEBUG)/bin/MainMenuState.o: bin/MainMenuState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bin/MainMenuState.cpp -o $(OBJDIR_DEBUG)/bin/MainMenuState.o

$(OBJDIR_DEBUG)/bin/SplashState.o: bin/SplashState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bin/SplashState.cpp -o $(OBJDIR_DEBUG)/bin/SplashState.o

$(OBJDIR_DEBUG)/bin/StateMachine.o: bin/StateMachine.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c bin/StateMachine.cpp -o $(OBJDIR_DEBUG)/bin/StateMachine.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/bin

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/bin || mkdir -p $(OBJDIR_RELEASE)/bin

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/bin/Collision.o: bin/Collision.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bin/Collision.cpp -o $(OBJDIR_RELEASE)/bin/Collision.o

$(OBJDIR_RELEASE)/bin/Game.o: bin/Game.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bin/Game.cpp -o $(OBJDIR_RELEASE)/bin/Game.o

$(OBJDIR_RELEASE)/bin/GameOverState.o: bin/GameOverState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bin/GameOverState.cpp -o $(OBJDIR_RELEASE)/bin/GameOverState.o

$(OBJDIR_RELEASE)/bin/GameState.o: bin/GameState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bin/GameState.cpp -o $(OBJDIR_RELEASE)/bin/GameState.o

$(OBJDIR_RELEASE)/bin/AssetManager.o: bin/AssetManager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bin/AssetManager.cpp -o $(OBJDIR_RELEASE)/bin/AssetManager.o

$(OBJDIR_RELEASE)/bin/InputManager.o: bin/InputManager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bin/InputManager.cpp -o $(OBJDIR_RELEASE)/bin/InputManager.o

$(OBJDIR_RELEASE)/bin/MainMenuState.o: bin/MainMenuState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bin/MainMenuState.cpp -o $(OBJDIR_RELEASE)/bin/MainMenuState.o

$(OBJDIR_RELEASE)/bin/SplashState.o: bin/SplashState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bin/SplashState.cpp -o $(OBJDIR_RELEASE)/bin/SplashState.o

$(OBJDIR_RELEASE)/bin/StateMachine.o: bin/StateMachine.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c bin/StateMachine.cpp -o $(OBJDIR_RELEASE)/bin/StateMachine.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/bin

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

